package co.edu.icesi.drools;

import co.edu.icesi.drools.Persona;

rule "Herpes genital fuerte"
	when
		persona: Persona(llagas=="Si",ubicacionLlagas=="vagina", ardorOrinar=="Si", dificultadOrinar=="Si", picazon=="Si", lugarPicazon=="vagina", dolorAreaGenital=="Si")
	then
		persona.setDiagnostico("Herpes genital fuerte");
end

rule "Herpes genital leve"
	when
		persona: Persona(llagas=="Si", ubicacionLlagas=="vulva",ardorOrinar=="No", dificultadOrinar=="No", picazon=="Si", lugarPicazon=="vagina", dolorAreaGenital=="Si")
	then
		persona.setDiagnostico("Herpes genital leve");
end

rule "Herpes genital VHS-2"
	when
		persona: Persona((inflamacionGlandulasPelvis=="Si"|| inflamacionGlandulasGarganta=="Si"|| inflamacionGlandulasAxilas=="Si"), fiebre=="Si", escalofrios=="Si", 
		dolorCabeza=="Si", cansancio=="Si")
	then
		persona.setDiagnostico("Herpes genital causado por el VHS-2");
end

rule "Descarta herpes genital"
	when
		persona: Persona(llagas=="No", ardorOrinar=="No", dificultadOrinar=="No", picazon=="No", dolorAreaGenital=="No")
	then
		persona.setDiagnostico("Descarta Herpes genital");
end
