package co.edu.icesi.rules;

import co.edu.icesi.drools.Persona;

rule "Clamidia preocupante-mujer"
    when
    	persona: Persona(dolorOrinar== "Si", dolorSexo == "Si", flujoVaginal=="anormal",
    		colorFlujo== "con sangre", dolorVientre== "Si", olorFlujo== "fuerte", sangrado== "Si", 
    		(lugarSangrado== "vagina" || lugarSangrado== "ano"), dolorAno== "Si", secrecionAno=="Si")
     then
        persona.setDiagnostico("Clamidia preocupante (Mujer)");
end

rule "Clamidia preocupante-hombre"
    when
        persona: Persona(dolorOrinar== "Si", dolorSexo == "Si", sangrado== "Si", 
    		lugarSangrado== "ano", dolorAno== "Si", secrecionAno=="Si", pusPene== "Si",
    		secrecionPene=="lechosa", sensibilidadTesticulos=="Si", inflamacionTesticulos=="Si")
     then
        persona.setDiagnostico("Clamidia preocupante (Hombre)");
end

rule "Clamidia leve-mujer"
    when
    	persona: Persona(dolorOrinar== "Si", dolorSexo == "Si", flujoVaginal=="anormal",
    		colorFlujo== "amarillento", dolorVientre== "Si", olorFlujo== "fuerte", sangrado== "No", 
    		dolorAno== "Si", secrecionAno=="No")
     then
        persona.setDiagnostico("Clamidia leve (Mujer)");
end

rule "Clamidia leve-hombre"
    when
    	persona: Persona(dolorOrinar== "Si", dolorSexo == "Si", sangrado== "No", 
    		dolorAno== "Si", secrecionAno=="Si", pusPene== "Si",
    		secrecionPene=="acuosa", sensibilidadTesticulos=="Si", inflamacionTesticulos=="Si")
     then
        persona.setDiagnostico("Clamidia leve (Hombre)");
end

rule "Descarta clamidia-mujer"
    when
    	persona: Persona(dolorOrinar== "No", dolorSexo == "No", flujoVaginal=="normal",
    		colorFlujo== "normal", dolorVientre== "No", olorFlujo== "normal", sangrado== "No", 
    		dolorAno== "No", secrecionAno=="No")
     then
        persona.setDiagnostico("Descarta Clamidia (Mujer)");
end

rule "Descarta clamidia-hombre"
    when
    	persona: Persona(dolorOrinar== "No", dolorSexo == "No", sangrado== "No", 
    		dolorAno== "No", secrecionAno=="No", pusPene== "No",
    		sensibilidadTesticulos=="No", inflamacionTesticulos=="No")
     then
        persona.setDiagnostico("Descarta Clamidia(Hombre)");
end