package co.edu.icesi.rules;

import co.edu.icesi.drools.Persona;

rule "Gonorrea fuerte"
	when
		persona: Persona(dolorOrinar=="Si", ardorOrinar=="Si", flujoVaginal=="anormal", colorFlujo=="amarillento", sangrado=="Si", 
		lugarSangrado=="vagina", picazon== "Si", lugarPicazon== "ano", secrecionAno=="Si", dolorDefecar=="Si")
	then
		persona.setDiagnostico("Gonorrea fuerte");
end

rule "Gonorrea leve"
	when
		persona: Persona(dolorOrinar=="Si", ardorOrinar=="Si", flujoVaginal=="anormal", colorFlujo=="amarillento", sangrado=="Si", 
		lugarSangrado=="vagina", picazon== "No",secrecionAno=="No", dolorDefecar=="No")
	then
		persona.setDiagnostico("Gonorrea leve");
end

rule "Descarta Gonorrea"
	when
		persona: Persona(dolorOrinar=="No", ardorOrinar=="No", flujoVaginal=="normal", colorFlujo=="normal", sangrado=="No", 
		picazon=="No", secrecionAno=="No", dolorDefecar=="No")
	then
		persona.setDiagnostico("Descarta Gonorrea");
end
