package co.edu.icesi.rules;

import co.edu.icesi.drools.Persona;

rule "Tricomoniasis fuerte-mujer"
	when
		persona: Persona(flujoVaginal=="anormal", (colorFlujo=="verde"|| colorFlujo=="amarillento" || colorFlujo=="gris"), olorFlujo=="fetido", 
		sangrado=="Si", lugarSangrado=="vagina", picazon=="Si", lugarPicazon=="vagina", dolorSexo=="Si")
	then
		persona.setDiagnostico("Tricomoniasis fuerte");
end

rule "Tricomoniasis leve- mujer"
	when
		persona: Persona(flujoVaginal== "anormal",(colorFlujo=="verde"|| colorFlujo=="amarillento" || colorFlujo=="gris"), olorFlujo=="fuerte", 
		sangrado=="No", picazon=="Si", lugarPicazon=="vagina", dolorSexo=="No")
	then
		persona.setDiagnostico("Tricomoniasis leve");
end


rule "Descarta Tricomoniasis"
	when
		persona: Persona(flujoVaginal=="normal", colorFlujo=="normal", olorFlujo=="normal", 
		sangrado=="No", picazon=="No", dolorSexo=="No")
	then
		persona.setDiagnostico("Descarta Tricomoniasis");
end