package co.edu.icesi.rules;

import co.edu.icesi.drools.Persona;

rule "VIH fuerte"
	when 
		persona: Persona (aftas=="Si", dolorGarganta=="Si", infeccionHongos=="Si", enfermedadPelvica=="cronica", infecciones=="recurrentes", 
		cansancio=="Si", mareos=="Si", dolorCabeza=="Si", perdidaPeso=="Si", formacionHematomas=="frecuente", diarrea=="Si", fiebre=="Si", sudores=="Si", 
		(inflamacionGlandulaPelvis=="Si"|| inflamacionGlandulaGarganta=="Si"|| inflamacionGlandulaAxilas=="Si"), tos=="seca", respiracion=="falta de aire", 
		llagas=="Si", (ubicacionLlagas=="piel" || ubicacionLlagas=="boca"), sangrado=="Si", (lugarSangrado=="boca"|| lugarSangrado=="ano" || lugarSangrado=="vagina"),
		fuerzaMuscular=="debil" )
	then
		persona.setDiagnostico("VIH fuerte");
end

rule "VIH leve"
	when 
		persona: Persona (aftas=="No", dolorGarganta=="Si", infeccionHongos=="Si", infecciones=="recurrentes", 
		cansancio=="Si", mareos=="Si", dolorCabeza=="Si", perdidaPeso=="No", formacionHematomas=="poco", diarrea=="No", fiebre=="Si", sudores=="Si", 
		(inflamacionGlandulaPelvis=="Si"|| inflamacionGlandulaGarganta=="Si"|| inflamacionGlandulaAxilas=="Si"), tos=="seca", respiracion=="falta de aire", 
		llagas=="Si",( ubicacionLlagas=="piel" || ubicacionLlagas=="boca"), sangrado=="No", fuerzaMuscular=="debil" )
	then
		persona.setDiagnostico("VIH Leve");
end

rule "Descarta VIH"
	when 
		persona: Persona (aftas=="No", dolorGarganta=="No", infeccionHongos=="No", cansancio=="No", mareos=="No", dolorCabeza=="No", perdidaPeso=="No", formacionHematomas=="No", diarrea=="No", fiebre=="No", sudores=="No", 
		inflamacionGlandulaPelvis=="No", inflamacionGlandulaGarganta=="No", inflamacionGlandulaAxilas=="No",respiracion=="Normal", 
		llagas=="No", sangrado=="No", fuerzaMuscular=="normal" )
	then
		persona.setDiagnostico("Descarta VIH");
end